{{- if .Values.initialization.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rustfs.fullname" . }}-init
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        {{- include "rustfs.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "rustfs.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: init
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          image: amazon/aws-cli:latest
          command:
            - /bin/sh
            - -c
            - |
              # Use the regular (ClusterIP) service name — this has a stable endpoint
              endpoint="http://{{ include "rustfs.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:9000"
              # Use /tmp for AWS config (writable for non-root)
              export AWS_CONFIG_FILE=/tmp/aws-config
              export AWS_SHARED_CREDENTIALS_FILE=/tmp/aws-credentials
              aws configure set aws_access_key_id "$ROOT_ACCESS_KEY"
              aws configure set aws_secret_access_key "$ROOT_SECRET_KEY"
              aws configure set region {{ .Values.s3region }}

              echo "Waiting for RustFS to be ready at $endpoint/health..."

              # Retry loop: check /health endpoint until it returns 200 OK
              until curl -f -s "$endpoint/health" > /dev/null; do
                echo "RustFS not ready yet, retrying in 2 seconds..."
                sleep 2
              done

              echo "RustFS is ready! Proceeding with bucket creation."

              echo "Creating buckets via $endpoint"

              {{- range .Values.initialization.buckets }}
              echo "Creating bucket: {{ . }}"
              aws --endpoint-url "$endpoint" s3 mb s3://{{ . | quote }} || true
              {{- end }}

              echo "Bucket initialization complete!"
          env:
            - name: ROOT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.fullname" . }}-secrets
                  key: access-key
            - name: ROOT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.fullname" . }}-secrets
                  key: secret-key
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
