apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rustfs.fullname" . }}
  labels:
    {{- include "rustfs.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "rustfs.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rustfs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "rustfs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rustfs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: rustfs
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --address
            - ":9000"
            - --access-key
            - $(RUSTFS_ACCESS_KEY)
            - --secret-key
            - $(RUSTFS_SECRET_KEY)
            - /data
          ports:
            - name: api
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          env:
            - name: RUSTFS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.fullname" . }}-secrets
                  key: access-key
            - name: RUSTFS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "rustfs.fullname" . }}-secrets
                  key: secret-key
            - name: RUSTFS_REGION
              value: "{{ .Values.s3region }}"
{{- if gt ( int  .Values.replicaCount ) 1 }}
            - name: RUSTFS_VOLUMES
              value: >-
                {{- $root := . }}
                {{- $fullname := include "rustfs.fullname" $root }}
                {{- $headless := printf "%s-headless" $fullname }}
                {{- $ns := $root.Release.Namespace }}
                {{- $start := 0 }}
                {{- $end := sub (int .Values.replicaCount) 1 }}
                http://{{ $fullname }}-{0...{{ $end }}}.{{ $headless }}.{{ $ns }}.svc.cluster.local:9000/data
                {{- end }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          startupProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: api
            initialDelaySeconds: 5
            periodSeconds: 5
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "rustfs.labels" . | nindent 10 }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
